config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :events do
    resources :comments
    post :confirm, on: :collection
  end
  resources :notifications, only: [:index]
  resources :favorites, only: [:create, :destroy]
  resources :users
  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  root 'top#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  has_many :notifications, dependent: :destroy
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @event = @comment.event
    @notification = @comment.notifications.build(user_id: @event.user.id )
    respond_to do |format|
      if @comment.save
       format.html { redirect_to event_path(@event), notice: 'コメントを投稿しました。' }
       format.js { render :index }
       unless @comment.event.user_id == current_user.id
         Pusher.trigger("user_#{@comment.event.user_id}_channel", 'comment_created', {
            message: 'あなたの作成した日記にコメントが付きました'
          })
       end
       Pusher.trigger("user_#{@comment.event.user_id}_channel", 'notification_created', {
          unread_counts: Notification.where(user_id: @comment.event.user.id, read: false).count
        })
      else
        format.html { render :new }
      end
    end
  end

  def edit
   @comment = Comment.find(params[:id])
   @event = @comment.event
  end

  def update
    @comment = Comment.find(params[:id])
    @blog = @comment.event
    if @comment.update(comment_params)
      redirect_to events_path, notice: "コメントを更新しました！"
    else
      render 'symbol'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.destroy
        format.html { redirect_to blog_path(@comment), notice: 'コメントを削除しました。' }
        format.js { render :index }
      else
        format.html { render :new }
      end
    end
  end


  private
    def comment_params
      params.require(:comment).permit(:event_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@event,@comment], remote: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= comment.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :event_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <blockquote>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        </blockquote>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_event_comment_path(event, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', event_comment_path(event, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <%= form_for([@event, @comment], url: event_comment_url) do |f| %>
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
    <%= f.submit '更新', class: 'btn btn-primary btn-block'  %>
    <% end %>
  </div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.event.comments, event: @comment.event }) %>")
$(':text').val('')