config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :events do
    resources :comments
    post :confirm, on: :collection
  end
  resources :notifications, only: [:index]
  resources :favorites, only: [:create, :destroy]
  resources :users
  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  root 'top#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin
      can :manage, :all           
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  has_many :notifications, dependent: :destroy
  validates :content, presence: true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, scope: :recipient_id
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

  

  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorite_user(user_id)
   favorites.find_by(user_id: user_id)
  end
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :event, counter_cache: :favorite_count

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
  validates :body, presence: true

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  mount_uploader :avatar, AvatarUploader
  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :favorites, dependent: :destroy

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @search = User.ransack(params[:q])
    @result = @search.result
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?
    
    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_events_path
    elsif action_name == 'edit'
      event_path
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
  <title>Daikadai6</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if user_signed_in? %>
    <script>
      var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
        encrypted: true,
        cluster: 'ap1'
      });

      var channel = pusher.subscribe("user_<%= current_user.id %>_channel");
      channel.bind('comment_created', function(data) {
        alert(data.message);
      });
      channel.bind('notification_created', function(data) {
        $('#unread_count').html(data.unread_counts);
      });
    </script>
  <% end %>
</head>
<body>
  <header>
      <ul>
       <li><%= link_to "トップページ", root_path %></li>
      <% if user_signed_in? %>
       <li><%= link_to "日記一覧", events_path %></li>
       <li><%= link_to 'ユーザー一覧', users_path %></li>
       <li><%= link_to "メッセージ", conversations_path %></li>
       <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
       <%= link_to notifications_path, class: "navbar-brand" do %>
        <i class="fa fa-bell fa-1x"><span id="unread_count"><%= @notifications_count %></span></i>
       <% end %>
      <% else %>
       <li><%= link_to 'ログイン', new_user_session_path %></li>
       <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
     </ul>
  </header>

<%= yield %>

  <footer>
    <p>運営会社DIVE INTO CODE株式会社の受講生</p>
  </footer>

</body>
</html>